# Site
repository: m-walters/m-walters.github.io
favicon: /assets/logo-candy.png

# Personal info
name: Michael Walters
# title: Physicist, AI Safety Researcher, Occasional Photographer
title: AI for safety, safety for AI
email: mw[at]gaia-lab[dot]de
#phone: +1 519-949-4428
profile: m-walters.github.io

# Social links
github_username: m-walters
instagram_username: ~
linkedin_username: michaelwalters3000

# About Section
about_title: About
about_profile_image: "/assets/images/autumn-selfie.png"
about_content: | # this will include new lines to allow paragraphs
  
  I'm interested in next-gen agentic AI systems that incorporate robust world models into their architectures.
  World models quantify an agent's uncertainty in its beliefs, provides transparency for us to view how
  an agent models its world, and in turn allows for safer operations and better value convergence.
  <br/>
  
  This is one of the technologies foundational to our architecture at the [GAIA Lab](https://www.gaia-lab.de/).
  Our mission is to unify systems through [federated active inference](https://www.sciencedirect.com/science/article/pii/S0149763423004694), 
  converging on ever-improving world models that are crafted with LLM-in-the-loop processes.
  Ultimately, this compiled encyclopedic "Github of world models" bolsters a symbolic world representation
  for improved and safer AI operations.
  <br/>
  
  I also write about various AI subjects and interests on my blog [Quarry](https://quarryblog.substack.com/).
  Overall, I would say I'm a sober moderate regarding AI threat models.
  My concern bends towards nearer-term harms (dis-/misinformation, malicious actors, 
  socioeconomic disparities and power concentration, etc.) vs. catastrophic x-risk scenarios 
  (though I don't rate all x-risk events as sufficiently ignorable).
  <br/>

  When I can, I enjoy taking my Olympus OM-1 along with me outdoors for some urban and nature photography.  

# Projects Section
projects_title: Misc. #(Use this to override about projects section title)

# Education Section
education_title: Almae Matres

# Experience Section
experience_title: Past & Ongoing

# More Section
more_title: Works & Publications #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  - M. Walters, R. Kaufmann, F. Neubürger, T. Kopinski, D. Marković, _The CRISTAL Method: Fast, reliable analytical problem-solving with pre-synthesized grounded world models_ (2025). [Read pdf](assets/cristal_benchmarking.pdf).
  - M. Walters, R. Kaufmann, J. Sefas, T. Kopinski. _Free Energy Risk Metrics for Systemically Safe AI: Gatekeeping Multi-agent Study_ (2025). [Read pdf](assets/AV_risk_MW_etal_v1.pdf). 
  - [RiskRay](/assets/risk_ray_summary.pdf) (Patented). Using ML to detect hips at risk of fracture.
  - Traffic prediction Graph Neural Net. View the proof-of-concept [toy model](https://github.com/m-walters/traffic_graphnn_toy).
  - My MSc. thesis: _Machine learning topological defects of liquid crystals
  in two dimensions._ Available online on [UWSpace](http://hdl.handle.net/10012/14949) (2019).
  - M. Walters, Q. Wei, J. Z. Y. Chen. _Machine learning topological defects of confined liquid crystals
  in two dimensions._ ([Phys. Rev. E 99, 062701](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.99.062701?fbclid=IwAR0aaXGnTeYb_p7BAYYYKBftRkI0hv_m88w3ieR3-CnvLsaGrr0GnfhiAbo) / [Read PDF](/assets/walters_2019_final.pdf)) (2019).
  - M. B. Bennett _et al. Detailed study of the decay $$^{31}Cl(\beta\gamma)^{31}S$$_. Physical Review C 97 (6), 065803 (2018).
  - E. Aboud _et al. Toward complete spectroscopy using $$\beta$$ decay: The example of $$^{32}Cl(\beta\gamma)^{32}S$$._ Physical Review C 98 (2), 024309 (2018). 
  - [Editors' suggestion] M. B. Bennett _et al. Isospin mixing reveals $$^{30}P(p,\gamma)^{31}S$$ resonance influencing nova nucleosynthesis._
  Phys. Rev. Lett. 116, 102502, (2016).
  - M. B. Bennett _et al. Isobaric multiplet mass equation in the $$A = 31, T = 3/2$$ quartets._ Physical Review C 93 (6), 064310 (2016).
  - C. Wrede _et al. $$\beta$$ Decay as a Probe of Explosive Nucleosynthesis in Classical Novae._ Physics Procedia 66, 532-536 (2015).
  

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
