# Site
repository: m-walters/m-walters.github.io
favicon: /assets/logo-candy.png

# Personal info
name: Michael Walters
title: Physicist, AI Safety Researcher, Occasional Photographer
email: michaelwalters3000@gmail.com
#phone: +1 519-949-4428
profile: m-walters.github.io

# Social links
github_username: m-walters
instagram_username: ~
linkedin_username: michaelwalters3000

# About Section
about_title: About
about_profile_image: "/assets/images/corridor_zoom_2.png"
about_content: | # this will include new lines to allow paragraphs
  
  Things that get me out of bed in the morning: Solving problems with math, science, and coding; Collaborating towards meaningful, impacting projects; Coffee.  
  <br/>
  My current focus is on probabilistic agentic AI systems. 
  In particular, probabilistic programming, Bayesian methods, and experimenting with Active Inference and Variational Free Energy-directed learning structures—mathematical formulations 
  entwining concepts from physics first-principles with theories of intelligence.  
  <br/>
  I also have an interest in AI safety efforts, with a bent towards near(er) term harms (misinformation, malicious actors, socioeconomic disparities, etc.) vs. catastrophic x-risk scenarios 
  (though I don't rate such events as safely ignorable). 
  I'm a recent alum from the SPAR research program, and am an active participant and volunteer in the [AI Governance & Safety Canada](https://aigs.ca) (AIGS) group, looking to ensure
  positive outcomes for AI in, and from, Canada.  
  <br/>
  In past work, I was as Senior Backend Developer at [QED](http://qed.software/), developing genericized platform tools and architecture
  for custom instantiation in business and data management contexts. [Since 2022](https://www.linkedin.com/posts/link-alliance_innovation-safety-cityraillink-activity-7057493881868750848-1pwn/?originalSubdomain=nz)
  QED has been creating custom software for New Zealand's 
  ["largest transport infrastructure project ever"](https://www.cityraillink.co.nz/#:~:text=Introducing%20the%20CRL&text=The%20%245.493%20billion%20project%20is,Station%20on%20the%20Western%20Line.).
  In other work placements, I joined the [Hyper-K](http://https://www-sk.icrr.u-tokyo.ac.jp/en/hk/) 
  neutrino detecting efforts&mdash;the successor to the 2015 Nobel Prize winner 
  Super-K&mdash;at Canada's premier accelerator lab, 
  [TRIUMF](https://www.triumf.ca); researched galactic cloud astrophysics via simulation at McMaster University with [James Wadsley's group](https://physics.mcmaster.ca/~wadsley/); 
  and worked on an anomaly detection ML model at Canada's Communications Security Establishment. I am also an extended volunteer for [Climate Change AI](https://www.climatechange.ai/).  
  <br/>
  Outside academic and professional pursuits, I love hosting and making food for friends and family; taking my Olympus OM-1 outdoors for some
  film shooting (though my bank account would prefer I don't); Volunteering at [The Local Community Food Centre](https://thelocalcfc.org); 
  and masochistically running Linux on my PC.  
  <br/>
  I also write weekly on AI/AI Safety papers on my substack, [Weekly Aligned](https://www.weeklyaligned.com).

  <br/>
  Software proficiencies: __Python, ML, Simulations, HPE, Django, Bash, DevOps, $$\LaTeX$$, Git, C++, MATLAB, R__  
  Frequently used Python libraries: __numpy, pandas, xarray, scipy, seaborn, tensorflow, pytorch, huggingface, scikit, pymc__  
  Tertiary experience: __HTML, Vue, SQL, Postgres, Geant4, ROOT__   

# Projects Section
projects_title: Misc. #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
education_title: Education

# More Section
more_title: Projects & Publications #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  - AI/AI Safety paper reviews on my substack, [Weekly Aligned](https://www.weeklyaligned.com).
  - Volunteering with [AIGS](https://aigs.ca): Contributions to the weekly Toronto AI Safety Meetup, and various website improvement efforts.  
  - [RiskRay](/assets/risk_ray_summary.pdf). Using ML to detect hips at risk of fracture. _Patent pending._
  - Traffic prediction Graph Neural Net. View the proof-of-concept [toy model](https://github.com/m-walters/traffic_graphnn_toy).
  - My MSc. thesis: _Machine learning topological defects of liquid crystals
  in two dimensions._ Available online on [UWSpace](http://hdl.handle.net/10012/14949) (2019).
  - M. Walters, Q. Wei, J. Z. Y. Chen. _Machine learning topological defects of confined liquid crystals
  in two dimensions._ ([Phys. Rev. E 99, 062701](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.99.062701?fbclid=IwAR0aaXGnTeYb_p7BAYYYKBftRkI0hv_m88w3ieR3-CnvLsaGrr0GnfhiAbo) / [Read PDF](/assets/walters_2019_final.pdf)) (2019).
  - M. B. Bennett _et al. Detailed study of the decay $$^{31}Cl(\beta\gamma)^{31}S$$_. Physical Review C 97 (6), 065803 (2018).
  - E. Aboud _et al. Toward complete spectroscopy using $$\beta$$ decay: The example of $$^{32}Cl(\beta\gamma)^{32}S$$._ Physical Review C 98 (2), 024309 (2018). 
  - [Editor's suggestion] M. B. Bennett _et al. Isospin mixing reveals $$^{30}P(p,\gamma)^{31}S$$ resonance influencing nova nucleosynthesis._
  Phys. Rev. Lett. 116, 102502, (2016).
  - M. B. Bennett _et al. Isobaric multiplet mass equation in the $$A = 31, T = 3/2$$ quartets._ Physical Review C 93 (6), 064310 (2016).
  - C. Wrede _et al. $$\beta$$ Decay as a Probe of Explosive Nucleosynthesis in Classical Novae._ Physics Procedia 66, 532-536 (2015).
  

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
