# Site
repository: m-walters/m-walters.github.io
favicon: /assets/logo-candy.png
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Michael Walters
title: Physicist, Developer, Sometimes Photographer
email: michaelwalters3000@gmail.com
phone: +1 519-949-4428
website: m-walters.github.io

# Social links
github_username: m-walters
instagram_username: hotdoglipstick
linkedin_username: michaelwalters3000

# About Section
about_title: About
about_profile_image: "/assets/images/garage_sqr_zoom.png"
about_content: | # this will include new lines to allow paragraphs
  
  Things that get me out of bed in the morning: Solving problems in math, science, and coding; Collaborating towards meaningful, impacting projects; Coffee.  
  I'm currently looking for a position where I can apply my skills in math/physics/software towards something meaningful, and which has a clear
  benefit to human wellness and/or the environment and its denizens. Areas such as sustainable energy, climate change, health, economic disparity, and topics surrounding
  AI safety all fit the bill.
  <br/>
  Academically, my latest vocation was a MSc. Physics at the University of Waterloo, where 
  my research sat at the intersection of machine learning
  and condensed matter. More details on that below.  
  <br/>
  My latest position was as Senior Backend Developer at [QED](http://qed.software/), where we provided a suite of administrative tools and performance metrics for businesses.
  In other work placements, I joined the [Hyper-K](http://https://www-sk.icrr.u-tokyo.ac.jp/en/hk/) 
  neutrino detecting efforts&mdash;the successor to the 2015 Nobel Prize winner 
  Super-K&mdash;at Canada's premier accelerator lab, 
  [TRIUMF](https://www.triumf.ca); researched galactic cloud astrophysics via simulation at McMaster University with [James Wadsley's group](https://physics.mcmaster.ca/~wadsley/); 
  and worked on an anomaly detection ML model at Canada's Communications Security Establishment.  
  <br/>
  Outside academic and professional pursuits, I love hosting and making food for friends and family; taking my Olympus OM-1 outdoors for some
  film shooting (though my bank account would prefer I don't); Volunteering at [The Local Community Food Centre](https://thelocalcfc.org); 
  and masochistically running Linux on my PC.  
  <br/> 
  My strongest software skills are: __Python, Django, Tensorflow, Bash, $$\LaTeX$$, Git, C++, MATLAB, R__
  Frequently used Python libraries: __numpy, pandas, matplotlib, scikit-learn__  
  I also have experience in: __SQL, Postgres, Geant4, ROOT__   


# Projects Section
projects_title: Misc. #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Projects & Publications #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  - \[Patent Pending\] [RiskRay](/assets/risk_ray_summary.pdf). Using ML to detect hips at risk of fracture.
  - Traffic prediction Graph Neural Net. View the proof-of-concept [toy model](https://github.com/m-walters/traffic_graphnn_toy).
  - My MSc. thesis: _Machine learning topological defects of liquid crystals
  in two dimensions._ Available online on [UWSpace](http://hdl.handle.net/10012/14949) (2019).
  - M. Walters, Q. Wei, J. Z. Y. Chen. _Machine learning topological defects of confined liquid crystals
  in two dimensions._ ([View on Phys. Rev. E](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.99.062701?fbclid=IwAR0aaXGnTeYb_p7BAYYYKBftRkI0hv_m88w3ieR3-CnvLsaGrr0GnfhiAbo) / [Read PDF](/assets/walters_2019_final.pdf)) (2019).
  - [Editor's suggestion] M. B. Bennett _et al._ (24 authors). _Isospin mixing reveals $$^{30}P(p,\gamma)^{31}S$$ resonance influencing nova nucleosynthesis._
  Phys. Rev. Lett. 116, 102502, (2016).
  

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
