# Site
repository: m-walters/m-walters.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Michael Walters
title: MSc. Physics
email: michaelwalters3000@gmail.com
phone: +1 519-949-4428
website: m-walters.github.io
github: m-walters

# Social links
#github_username: m-walters
#instagram_username: hotdoglipstick
#linkedin_username: michaelwalters3000

# About Section
about_title: " "
about_profile_image: "/assets/images/selfie-square-zoom.JPG"
about_content: | # this will include new lines to allow paragraphs
  
  Academically, I recently finished my MSc. Physics at the University of Waterloo, where 
  my research sat at the intersection of machine learning
  and condensed matter. More details are given below.  
  <br/>
  In work placements, I joined Hyper-K's neutrino detecting efforts at 
  Canada's leading accelerator lab, TRIUMF, researched astrophysics 
  at McMaster University, and developed software at Canada's Communications Security Establishment.  
  <br/> 
  My strongest software skills are: __Python, C++, Bash, MATLAB, $$\LaTeX$$, Git__ (mostly private repos)  
  I also have experience in: __Maple, SQL, Postgres, Geant4, ROOT__  
  <br/>
  This CV is also hosted online at the website listed above and contains relevant hyperlinks.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Publications #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  - Traffic prediction Graph Neural Net. In progress on github. View the completed toy model at [https://github.com/m-walters/graphnn_toy](https://github.com/m-walters/graphnn_toy).
  - My MSc. thesis: _Machine learning topological defects of liquid crystals
  in two dimensions._ Available online at [http://hdl.handle.net/10012/14949](http://hdl.handle.net/10012/14949).
  - M. Walters, Q. Wei, J. Z. Y. Chen. _Machine learning topological defects of confined liquid crystals
  in two dimensions._ ([View on Phys. Rev. E](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.99.062701?fbclid=IwAR0aaXGnTeYb_p7BAYYYKBftRkI0hv_m88w3ieR3-CnvLsaGrr0GnfhiAbo) / [Read PDF](/assets/walters_2019_final.pdf))  
  - [Editor's suggestion] M. B. Bennett _et al._ (24 authors). _Isospin mixing reveals $$^{30}P(p,\gamma)^{31}S$$ resonance influencing nova nucleosynthesis._
  Phys. Rev. Lett. 116, 102502, (2016)
  

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
